<?php
//地区配置文件,对应数据库表ips中的prov_id与city_id
global $CONF_PROVINCE_SPELL;
$CONF_PROVINCE_SPELL = Array(
	34 => "anhui", 
	11 => "beijing", 
	50 => "chongqing", 
	35 => "fujian", 
	62 => "gansu", 
	44 => "guangdong", 
	45 => "guangxi", 
	52 => "guizhou", 
	46 => "hainan", 
	13 => "hebei", 
	23 => "heilongjiang", 
	41 => "henan", 
	42 => "hubei", 
	43 => "hunan", 
	15 => "neimenggu", 
	32 => "jiangsu", 
	36 => "jiangxi", 
	22 => "jilin", 
	21 => "liaoning", 
	64 => "ningxia", 
	63 => "qinghai", 
	14 => "shanx", 
	37 => "shandong", 
	31 => "shanghai", 
	51 => "sichuan", 
	12 => "tianjin", 
	54 => "xizang", 
	65 => "xinjiang", 
	53 => "yunnan", 
	33 => "zhejiang", 
	61 => "shanxi", 
	71 => "taiwan", 
	81 => "hongkong", 
	82 => "macau", 
	1  => "china",
	2  => "online",
	400 => "haiwai",
	401 => "sina"
);
?>
